# Generated by Django 4.0.1 on 2022-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='request_date',
            field=models.DateField(default='2022-03-10'),
            preserve_default=False,
        ),
    ]
