# Generated by Django 4.0.1 on 2022-04-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_customer_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(1, 'На рассмотрении'), (2, 'Одобрен'), (3, 'Отказано')]),
        ),
    ]
